# Generated by Django 6.0.1 on 2026-01-10 17:49

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('refresh_interval_seconds', models.IntegerField(default=5, help_text='Stats refresh interval')),
                ('default_jwt_expiry_hours', models.IntegerField(default=24)),
                ('enable_webhooks', models.BooleanField(default=True)),
                ('webhook_secret', models.CharField(blank=True, help_text='Secret for webhook validation', max_length=255)),
                ('dark_mode', models.BooleanField(default=True)),
                ('show_bandwidth_graphs', models.BooleanField(default=True)),
                ('max_recent_conferences', models.IntegerField(default=50)),
                ('notify_on_new_conference', models.BooleanField(default=False)),
                ('notify_on_high_load', models.BooleanField(default=True)),
                ('high_load_threshold', models.FloatField(default=0.8, help_text='Stress level threshold (0-1)')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Dashboard Settings',
                'verbose_name_plural': 'Dashboard Settings',
            },
        ),
        migrations.CreateModel(
            name='JitsiServer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('base_url', models.URLField(help_text='e.g., https://192.168.117.153')),
                ('colibri_port', models.IntegerField(default=8080)),
                ('jicofo_port', models.IntegerField(default=8888)),
                ('jibri_port', models.IntegerField(default=2222)),
                ('app_id', models.CharField(default='jitsi_dashboard', max_length=100)),
                ('app_secret', models.CharField(blank=True, help_text='Secret key for JWT tokens', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('is_primary', models.BooleanField(default=False, help_text='Primary server for new meetings')),
                ('verify_ssl', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Jitsi Server',
                'verbose_name_plural': 'Jitsi Servers',
                'ordering': ['-is_primary', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Conference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_name', models.CharField(db_index=True, max_length=255)),
                ('display_name', models.CharField(blank=True, help_text='Human-friendly meeting name', max_length=255)),
                ('status', models.CharField(choices=[('active', 'Active'), ('ended', 'Ended'), ('scheduled', 'Scheduled')], default='active', max_length=20)),
                ('is_password_protected', models.BooleanField(default=False)),
                ('has_lobby', models.BooleanField(default=False)),
                ('max_participants', models.IntegerField(default=0)),
                ('total_participants', models.IntegerField(default=0)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_recorded', models.BooleanField(default=False)),
                ('recording_url', models.URLField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_conferences', to=settings.AUTH_USER_MODEL)),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conferences', to='dashboard.jitsiserver')),
            ],
            options={
                'verbose_name': 'Conference',
                'verbose_name_plural': 'Conferences',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('participant_id', models.CharField(blank=True, help_text='Jitsi internal participant ID', max_length=100)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('is_moderator', models.BooleanField(default=False)),
                ('joined_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('left_at', models.DateTimeField(blank=True, null=True)),
                ('disconnect_reason', models.CharField(blank=True, help_text='Why participant left', max_length=50)),
                ('conference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='dashboard.conference')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='participations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Participant',
                'verbose_name_plural': 'Participants',
                'ordering': ['-joined_at'],
            },
        ),
        migrations.CreateModel(
            name='Recording',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recording_type', models.CharField(choices=[('file', 'File Recording'), ('stream', 'Live Stream'), ('local', 'Local Recording')], default='file', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('recording', 'Recording'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('session_id', models.CharField(max_length=255, unique=True)),
                ('file_path', models.CharField(blank=True, max_length=500)),
                ('file_size_mb', models.FloatField(default=0)),
                ('duration_seconds', models.IntegerField(default=0)),
                ('stream_url', models.URLField(blank=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('error_message', models.TextField(blank=True)),
                ('conference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recordings', to='dashboard.conference')),
            ],
            options={
                'verbose_name': 'Recording',
                'verbose_name_plural': 'Recordings',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WebhookEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('ROOM_CREATED', 'Room Created'), ('ROOM_DESTROYED', 'Room Destroyed'), ('PARTICIPANT_JOINED', 'Participant Joined'), ('PARTICIPANT_LEFT', 'Participant Left'), ('PARTICIPANT_JOINED_LOBBY', 'Participant Joined Lobby'), ('PARTICIPANT_LEFT_LOBBY', 'Participant Left Lobby'), ('RECORDING_STARTED', 'Recording Started'), ('RECORDING_STOPPED', 'Recording Stopped'), ('OTHER', 'Other')], max_length=50)),
                ('room_name', models.CharField(blank=True, db_index=True, max_length=255)),
                ('payload', models.JSONField(default=dict)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('processed', models.BooleanField(default=False)),
                ('server', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='webhook_events', to='dashboard.jitsiserver')),
            ],
            options={
                'verbose_name': 'Webhook Event',
                'verbose_name_plural': 'Webhook Events',
                'ordering': ['-received_at'],
            },
        ),
        migrations.AddIndex(
            model_name='conference',
            index=models.Index(fields=['room_name', 'server'], name='dashboard_c_room_na_95d909_idx'),
        ),
        migrations.AddIndex(
            model_name='conference',
            index=models.Index(fields=['status'], name='dashboard_c_status_daf3ad_idx'),
        ),
        migrations.AddIndex(
            model_name='conference',
            index=models.Index(fields=['started_at'], name='dashboard_c_started_de3c74_idx'),
        ),
        migrations.AddIndex(
            model_name='webhookevent',
            index=models.Index(fields=['event_type'], name='dashboard_w_event_t_46dbba_idx'),
        ),
        migrations.AddIndex(
            model_name='webhookevent',
            index=models.Index(fields=['received_at'], name='dashboard_w_receive_3db09c_idx'),
        ),
    ]
