# Generated by Django 4.2.11 on 2026-01-15 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RevokedRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_name', models.CharField(db_index=True, max_length=255, unique=True)),
                ('revoked_at', models.DateTimeField(auto_now_add=True)),
                ('reason', models.CharField(default='deleted', max_length=100)),
            ],
            options={
                'verbose_name': 'Revoked Room',
                'verbose_name_plural': 'Revoked Rooms',
                'ordering': ['-revoked_at'],
            },
        ),
    ]
